import { migrate } from "drizzle-orm/node-postgres/migrator";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import type { Db } from "./client.js";

// Migrations live at apps/control-api/drizzle (generated by drizzle-kit, committed).
export async function runMigrations(db: Db): Promise<void> {
  const here = dirname(fileURLToPath(import.meta.url));
  // dist/db -> ../../drizzle at runtime; src/db -> ../../drizzle in dev
  const folder = resolve(here, "../../drizzle");
  await migrate(db, { migrationsFolder: folder });
}
